<?php

namespace FS\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CustomerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getFindAllRaw()
    {
        return $this->createQueryBuilder('c')
            ->distinct(true)
            ->where('c.roles LIKE :roles')
            ->setParameter('roles', '%"ROLE_CUSTOMER"%')
            ->orderBy('c.fullName','ASC');
    }

    /**
     * @param array $criteria
     * @return array
     */
    public function findByUniqueCriteria(array $criteria)
    {
        // would use findOneBy() but Symfony expects a Countable object
        return $this->_em->getRepository('FSUserBundle:Customer')->findBy($criteria);
    }

	public function addFilterConditions($query, QueryBuilder $qb) {
		return $qb->andWhere(
			$qb->expr()->orX(
				'c.fullName LIKE :query',
				'c.phone LIKE :query',
				'c.company LIKE :query',
				'c.email LIKE :query'
			)
		)->setParameter('query', "%$query%");
	}
}
