<?php

namespace FS\TrainingProgramsBundle\Entity\Repository;


use Doctrine\ORM\EntityRepository;
use FS\TrainingProgramsBundle\Entity\TrainingProgram;
use FS\UserBundle\Entity\Vendor;


/**
 * TrainingRequestRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
    public function findRequestByVendorAndTrainingProgram(Vendor $vendor, TrainingProgram $trainingProgram)
    {
        return $this->createQueryBuilder('request')
                    ->leftJoin('request.vendor', 'vendor')
                    ->leftJoin('request.trainingProgram', 'trainingProgram')
                    ->where('vendor = :vendor')
                    ->andWhere('trainingProgram = :trainingProgram')
                    ->setParameters([
                        'vendor' => $vendor,
                        'trainingProgram' => $trainingProgram
                    ])
                    ->getQuery()->getOneOrNullResult();
    }
}
