<?php

namespace FS\TrainingProgramsBundle\Entity\Repository;


use Doctrine\ORM\EntityRepository;
use FS\TrainingProgramsBundle\Entity\Slide;
use FS\TrainingProgramsBundle\Entity\TrainingProgram;


/**
 * SlideRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SlideRepository extends EntityRepository
{
    public function getSlideByTrainingProgramAndRealNum(TrainingProgram $trainingProgram, $realNum = null)
    {
        return $this->createQueryBuilder('slide')
            ->where('slide.program = :trainingProgram AND slide.realNum = :realNum')
            ->setParameters([
                'trainingProgram' => $trainingProgram,
                'realNum' => $realNum > 0 ? $realNum : 1
            ])->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
    }

    public function countAllSlidesOfTrainingProgram(TrainingProgram $trainingProgram)
    {
        return $this->createQueryBuilder('slide')
            ->select('count(slide)')
            ->where('slide.program = :trainingProgram')
            ->setParameters([
                'trainingProgram' => $trainingProgram,
            ])->getQuery()->getSingleScalarResult();
    }

    public function getAllSlidesWithQuestionsByTrainingProgram(TrainingProgram $trainingProgram)
    {
        return $this->createQueryBuilder('slide')
            ->where('slide.program = :trainingProgram AND slide.slideType = :slideType')
            ->setParameters([
                'trainingProgram' => $trainingProgram,
                'slideType' => Slide::SLIDE_TYPE__QUESTION
            ])->getQuery()->getResult();
    }
}
