fs_training_programs:
    resource: "@FSTrainingProgramsBundle/Controller/"
    type:     annotation
    prefix:   /

fs_udoras:
    resource: "@FSUdorasBundle/Controller/"
    type:     annotation
    prefix:   /

fs_udoras_internal:
    resource: "@FSUdorasBundle/Controller/InternalController.php"
    type:     annotation
    prefix:   /internal
    defaults: { _format: 'json' }

fs_udoras_admin:
    resource: "@FSUdorasBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin

fs_udoras_customer:
    resource: "@FSUdorasBundle/Controller/Customer"
    type:     annotation
    prefix:   /customer

fs_udoras_vendor:
    resource: "@FSUdorasBundle/Controller/Vendor"
    type:     annotation
    prefix:   /vendor

fs_udoras_employee:
    resource: "@FSUdorasBundle/Controller/Employee"
    type:     annotation
    prefix:   /employee

fs_basic:
    resource: "@FSBasicBundle/Controller"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fs_user:
    resource: "@FSUserBundle/Controller"
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fs_user_security_login_success:
    path: /login-success
    defaults:
        _controller: FSUserBundle:Security:loginSuccess

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"