<?php

namespace FS\UdorasBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeleteQueueRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DeleteQueueRepository extends EntityRepository
{
}
